name: SonarQube Analysis

on:
  push:
    branches: ["master"]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install django==3.0.7

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Pizza-delivery-app
            -Dsonar.projectName=Pizza-delivery-app
            -Dsonar.sources=.
            -Dsonar.python.version=3.10
            -Dsonar.scanner.skipJreProvisioning=true
            -Dsonar.exclusions=**/venv/**,**/db.sqlite3,**/.idea/**,**/migrations/**
            -Dsonar.ws.additionalHeaders="Bypass-Tunnel-Reminder:true"